infra up

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,7 +17,7 @@ env:
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
   AWS_REGION: us-east-1
-  EKS_CLUSTER: kitops-eks
+  EKS_CLUSTER: vprofile-eks
 
 jobs:
     terraform:
@@ -58,5 +58,39 @@ jobs:
           if: steps.plan.outcome == 'failure'
           run: exit 1
 
-        - name: terraform destroy
-          run: terraform destroy -auto-approve -input=false
+        - name: terraform apply
+          id: apply
+          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+          run: terraform apply -auto-approve input=false -no-color parallelism=1 planfile
+
+        - name: Configure aws creds
+          uses: aws-actions/configure-aws-credentials@v1
+          with:
+            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+            aws-region: ${{ env.AWS_REGION }}
+
+        - name: Get kubeconfig and update it
+          id: getconfig
+          if: steps.apply.outcome == 'success'
+          run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}
+
+        - name: Install Ingress Controller/ Load Balancer
+          if: steps.apply.outcome == 'success' && steps.getconfig.outcome == 'success'
+          run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
+
+        - name: Inspecting kubeconfig
+          if: steps.getconfig.outcome == 'success'
+          run: |
+            echo "---------"
+            echo "1.Confirming File Existence"
+            ls -lh ~/.kube/config
+            echo "--------"
+            echo -e "\n2. The Full Configuration Structure."
+            kubectl config view
+            echo "--------"
+            echo -e "\n3. Proof Of Authentication Method."
+            # This extracts just the command block to show you exactly what executes
+            # It proves that 'kubectl' is just a wrapper triggering 'aws eks get-token'
+            grep -A 10 "exec:" ~/.kube/config || echo "Exec section not found"
+            echo "------------------------"
